### ISSUE TITLE
[Feature] Subscription plugin

### ISSUE THREAD

**Issue by NicoCG** [iDanScott/DiscordDotNet#1]
@iDanScott,

Love the work you have done on this discord bot!

Was wondering could you kindly add a plugin that involves subscription please see link below as example.

https://github.com/anlungu/KatieBot

**Comment by iDanScott** [comment]
https://github.com/iDanScott/DiscordDotNet/commit/2066bc1482f30d6afb21cbedea789c29b45f141f does this do it for you? If not it should be a good base to work from to add it into your own fork :)

**Comment by NicoCG** [comment]
Thanks @iDanScott that’s a good base to start from
