### ISSUE TITLE
[Question] Multiple commands within plugin

### ISSUE THREAD

**Issue by NicoCG** [iDanScott/DiscordDotNet#2]
@iDanScott,

How would I go by adding multiple commands to one instance of a plugin.

Example: If I will add to add to your plugin `PrivateMessage` where it will have two additional commands `!w` Whisper and `!r` reply to last Whisper.

Does the plugin support multiple commands eventually I would like to create plugins that allow you to `!kick`, `!ban` etc.

**Comment by iDanScott** [comment]
You can create another class (in a .cs file) that implements the `ICommandPlugin` interface and have that build into the class library of the class library. In your example I would just add `ReplyCommand.cs` or `KickCommand.cs` that implement the `ICommandPlugin` and if you want to have extra aliases for a command you could do something like I have done with this here https://github.com/iDanScott/DiscordDotNet/blob/master/DiscordDotNet.Plugins.PrivateMessage/PrivateMessageCommand.cs#L16 altering the behaviour of `CanHandle` to include more than one command

**Comment by NicoCG** [comment]
Thanks
